// Signal Monitor — seed data
// Realistic, niche, calm content. The kind a real user with specific interests would actually watch.

const SM_SEED = {
  subscriptions: [
    {
      id: 's1',
      query: 'blockchain meetups curitiba',
      type: 'event',
      cadence: '1h',
      lastRun: '2h ago',
      unread: true,
      pinned: true,
      signals: [
        {
          id: 'sg1',
          title: 'ETH Curitiba — June Builders Night',
          summary: 'Solidity workshop + lightning talks. Hosted at Worktiba Comendador. Free, RSVP via Luma.',
          source: 'lu.ma',
          time: '2h ago',
          day: 'Today',
          new: true,
        },
        {
          id: 'sg2',
          title: 'Web3 Brasil South Chapter forms in PR',
          summary: 'Regional chapter just announced; first event in Curitiba scheduled for July 12.',
          source: 'web3brasil.org',
          time: '5h ago',
          day: 'Today',
          new: true,
        },
        {
          id: 'sg3',
          title: 'Tezos Houseparty — Curitiba edition',
          summary: 'Casual meetup at Hocca Bar. Talks from 19:00, open mic after.',
          source: 'tezos.foundation',
          time: 'Yesterday',
          day: 'Yesterday',
        },
        {
          id: 'sg4',
          title: 'StarkNet Brazil hackathon — qualifier event',
          summary: 'Two-day in-person qualifier. PUCPR campus, registration closes May 30.',
          source: 'starknet.io',
          time: '3d ago',
          day: 'This week',
        },
      ],
    },
    {
      id: 's2',
      query: 'phoebe bridgers tour announcements',
      type: 'news',
      cadence: '6h',
      lastRun: '4h ago',
      unread: true,
      signals: [
        {
          id: 'sg5',
          title: 'Phoebe Bridgers adds South American leg for fall 2026',
          summary: 'São Paulo, Buenos Aires, Santiago confirmed. Pre-sale opens next Tuesday for Spotify subscribers.',
          source: 'pitchfork.com',
          time: '4h ago',
          day: 'Today',
          new: true,
        },
        {
          id: 'sg6',
          title: 'boygenius archive sessions to be released',
          summary: 'Surprise EP of demos and outtakes on June 7. No tour attached yet.',
          source: 'stereogum.com',
          time: 'Yesterday',
          day: 'Yesterday',
        },
      ],
    },
    {
      id: 's3',
      query: 'EU AI Act enforcement updates',
      type: 'news',
      cadence: '1d',
      lastRun: '8h ago',
      unread: false,
      signals: [
        {
          id: 'sg7',
          title: 'European Commission publishes Q2 enforcement guidance',
          summary: 'Clarifies obligations for general-purpose model providers. 47-page document, summary attached.',
          source: 'digital-strategy.ec.europa.eu',
          time: '8h ago',
          day: 'Today',
        },
        {
          id: 'sg8',
          title: 'France-based startup fined €350k for non-compliance',
          summary: 'First major fine under Article 52. Failure to disclose training data sources cited.',
          source: 'reuters.com',
          time: '2d ago',
          day: 'This week',
        },
      ],
    },
    {
      id: 's4',
      query: 'rare book auctions strand',
      type: 'event',
      cadence: '1d',
      lastRun: '12h ago',
      unread: false,
      signals: [
        {
          id: 'sg9',
          title: 'First-edition Borges collection — viewing June 14',
          summary: 'Strand auction house, in-person and online bidding. Reserve €40,000–€60,000.',
          source: 'strandbooks.com',
          time: '12h ago',
          day: 'Today',
        },
      ],
    },
    {
      id: 's6',
      query: 'oasis reunion tour san francisco',
      type: 'event',
      cadence: '1h',
      lastRun: '20m ago',
      unread: false,
      resolved: {
        title: 'Confirmed · Oracle Park · Sep 12, 2026',
        sub: 'Tickets on sale Friday. No more checks needed.',
        date: 'Sep 12',
      },
      signals: [
        {
          id: 'sg11',
          title: 'Oasis confirms two SF dates at Oracle Park',
          summary: 'September 12 and 13, 2026. Pre-sale Wednesday, general sale Friday at 10am PT via Ticketmaster.',
          source: 'oasisinet.com',
          time: '20m ago',
          day: 'Today',
          new: false,
        },
        {
          id: 'sg12',
          title: 'Stadium reunion run expands to North America',
          summary: 'Initial dates announced. SF added after demand survey from European leg.',
          source: 'rollingstone.com',
          time: '2d ago',
          day: 'This week',
        },
      ],
    },
    {
      id: 's5',
      query: 'lisbon coworking new openings',
      type: 'event',
      cadence: '6h',
      lastRun: '1d ago',
      unread: false,
      signals: [
        {
          id: 'sg10',
          title: 'Second Home Lisboa expansion to Príncipe Real',
          summary: 'Opening September. 1,200 sqm, garden access, day passes from €28.',
          source: 'secondhome.io',
          time: '1d ago',
          day: 'Yesterday',
        },
      ],
    },
  ],
};

window.SM_SEED = SM_SEED;
